indicators:
  # Indicators for Form 1
  - key: "hps-c-1"
    grouping: "HPS"
    expectedIndicators: [ "Fb2Xis54K99", "fkcCuN3W89f" ]
    description: "Shule za awali Serikali"
    indicatorQuery: " 	SELECT COALESCE((SELECT SUM(number_of_pre_schools_government) FROM ec_hps_annual_census_register WHERE year = substr('%s', 1, 4)), '0') AS count;"
