indicators:
  #  Question 1
  #  Male
  - key: "sbc-1-male-50+"
    description: "Number of individuals reached by specific SBC HIV community activity"
    indicatorQuery: "SELECT count(DISTINCT efm.base_entity_id) as count
                      FROM ec_sbc_register ear
                      INNER JOIN ec_family_member efm ON efm.base_entity_id = ear.base_entity_id
                      AND (date('now')-date(efm.dob))>=50
                      AND (efm.gender='Male')
                      AND date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01')) =
                      date(substr(strftime('%Y-%m-%d', datetime(last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||
                      '-' || substr(strftime('%Y-%m-%d', datetime(last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) || '-' || '01')"

  - key: "sbc-1-female-20-24"
    description: "Number of individuals reached by specific SBC HIV community activity"
    indicatorQuery: "SELECT count(DISTINCT efm.base_entity_id) as count
                      FROM ec_sbc_register ear
                      INNER JOIN ec_family_member efm ON efm.base_entity_id = ear.base_entity_id
                      AND (date(efm.dob, '+20 years') <= date('now'))
                      AND (date(efm.dob, '+24 years') > date('now'))
                      AND (efm.gender='Female')
                      AND date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01')) =
                      date(substr(strftime('%Y-%m-%d', datetime(last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||
                      '-' || substr(strftime('%Y-%m-%d', datetime(last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) || '-' || '01')"