indicators:
  #  Question 1
  #  Male
  - key: "sbc-1-male-10-14"
    description: "Number of individuals reached by specific SBC HIV community activity"
    indicatorQuery: "SELECT count(DISTINCT efm.base_entity_id) as count
                      FROM ec_sbc_register ear
					  INNER JOIN ec_family_member efm ON efm.base_entity_id = ear.base_entity_id
                      AND (date(efm.dob, '+10 years') <= date('now'))
                      AND (date(efm.dob, '+14 years') > date('now'))
                      AND (efm.gender='Male')
                      AND date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01')) =
                      date(substr(strftime('%Y-%m-%d', datetime(last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||
                      '-' || substr(strftime('%Y-%m-%d', datetime(last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) || '-' || '01')"

  - key: "sbc-1-male-15-19"
    description: "Number of individuals reached by specific SBC HIV community activity"
    indicatorQuery: "SELECT count(DISTINCT efm.base_entity_id) as count
                      FROM ec_sbc_register ear
                      INNER JOIN ec_family_member efm ON efm.base_entity_id = ear.base_entity_id
                      AND (date(efm.dob, '+15 years') <= date('now'))
                      AND (date(efm.dob, '+19 years') > date('now'))
                      AND (efm.gender='Male')
                      AND date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01')) =
                      date(substr(strftime('%Y-%m-%d', datetime(last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||
                      '-' || substr(strftime('%Y-%m-%d', datetime(last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) || '-' || '01')"

  - key: "sbc-1-male-20-24"
    description: "Number of individuals reached by specific SBC HIV community activity"
    indicatorQuery: "SELECT count(DISTINCT efm.base_entity_id) as count
                      FROM ec_sbc_register ear
                      INNER JOIN ec_family_member efm ON efm.base_entity_id = ear.base_entity_id
                      AND (date(efm.dob, '+20 years') <= date('now'))
                      AND (date(efm.dob, '+24 years') > date('now'))
                      AND (efm.gender='Male')
                      AND date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01')) =
                      date(substr(strftime('%Y-%m-%d', datetime(last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||
                      '-' || substr(strftime('%Y-%m-%d', datetime(last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) || '-' || '01')"

  - key: "sbc-1-male-25-29"
    description: "Number of individuals reached by specific SBC HIV community activity"
    indicatorQuery: "SELECT count(DISTINCT efm.base_entity_id) as count
                      FROM ec_sbc_register ear
                      INNER JOIN ec_family_member efm ON efm.base_entity_id = ear.base_entity_id
                      AND (date(efm.dob, '+25 years') <= date('now'))
                      AND (date(efm.dob, '+29 years') > date('now'))
                      AND (efm.gender='Male')
                      AND date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01')) =
                      date(substr(strftime('%Y-%m-%d', datetime(last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||
                      '-' || substr(strftime('%Y-%m-%d', datetime(last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) || '-' || '01')"

  - key: "sbc-1-male-30-34"
    description: "Number of individuals reached by specific SBC HIV community activity"
    indicatorQuery: "SELECT count(DISTINCT efm.base_entity_id) as count
                      FROM ec_sbc_register ear
                      INNER JOIN ec_family_member efm ON efm.base_entity_id = ear.base_entity_id
                      AND (date(efm.dob, '+30 years') <= date('now'))
                      AND (date(efm.dob, '+34 years') > date('now'))
                      AND (efm.gender='Male')
                      AND date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01')) =
                      date(substr(strftime('%Y-%m-%d', datetime(last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||
                      '-' || substr(strftime('%Y-%m-%d', datetime(last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) || '-' || '01')"

  - key: "sbc-1-male-35-39"
    description: "Number of individuals reached by specific SBC HIV community activity"
    indicatorQuery: "SELECT count(DISTINCT efm.base_entity_id) as count
                      FROM ec_sbc_register ear
                      INNER JOIN ec_family_member efm ON efm.base_entity_id = ear.base_entity_id
                      AND (date(efm.dob, '+35 years') <= date('now'))
                      AND (date(efm.dob, '+39 years') > date('now'))
                      AND (efm.gender='Male')
                      AND date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01')) =
                      date(substr(strftime('%Y-%m-%d', datetime(last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||
                      '-' || substr(strftime('%Y-%m-%d', datetime(last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) || '-' || '01')"

  - key: "sbc-1-male-40-44"
    description: "Number of individuals reached by specific SBC HIV community activity"
    indicatorQuery: "SELECT count(DISTINCT efm.base_entity_id) as count
                      FROM ec_sbc_register ear
                      INNER JOIN ec_family_member efm ON efm.base_entity_id = ear.base_entity_id
                      AND (date(efm.dob, '+40 years') <= date('now'))
                      AND (date(efm.dob, '+44 years') > date('now'))
                      AND (efm.gender='Male')
                      AND date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01')) =
                      date(substr(strftime('%Y-%m-%d', datetime(last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||
                      '-' || substr(strftime('%Y-%m-%d', datetime(last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) || '-' || '01')"

  - key: "sbc-1-male-45-49"
    description: "Number of individuals reached by specific SBC HIV community activity"
    indicatorQuery: "SELECT count(DISTINCT efm.base_entity_id) as count
                      FROM ec_sbc_register ear
                      INNER JOIN ec_family_member efm ON efm.base_entity_id = ear.base_entity_id
                      AND (date(efm.dob, '+45 years') <= date('now'))
                      AND (date(efm.dob, '+49 years') > date('now'))
                      AND (efm.gender='Male')
                      AND date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01')) =
                      date(substr(strftime('%Y-%m-%d', datetime(last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||
                      '-' || substr(strftime('%Y-%m-%d', datetime(last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) || '-' || '01')"

  - key: "sbc-1-male-50+"
    description: "Number of individuals reached by specific SBC HIV community activity"
    indicatorQuery: "SELECT count(DISTINCT efm.base_entity_id) as count
                      FROM ec_sbc_register ear
                      INNER JOIN ec_family_member efm ON efm.base_entity_id = ear.base_entity_id
                      AND (date('now')-date(efm.dob))>=50
                      AND (efm.gender='Male')
                      AND date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01')) =
                      date(substr(strftime('%Y-%m-%d', datetime(last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||
                      '-' || substr(strftime('%Y-%m-%d', datetime(last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) || '-' || '01')"
  #  Female
  - key: "sbc-1-female-10-14"
    description: "Number of individuals reached by specific SBC HIV community activity"
    indicatorQuery: "SELECT count(DISTINCT efm.base_entity_id) as count
                      FROM ec_sbc_register ear
                      INNER JOIN ec_family_member efm ON efm.base_entity_id = ear.base_entity_id
                      AND (date(efm.dob, '+10 years') <= date('now'))
                      AND (date(efm.dob, '+14 years') > date('now'))
                      AND (efm.gender='Female')
                      AND date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01')) =
                      date(substr(strftime('%Y-%m-%d', datetime(last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||
                      '-' || substr(strftime('%Y-%m-%d', datetime(last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) || '-' || '01')"

  - key: "sbc-1-female-15-19"
    description: "Number of individuals reached by specific SBC HIV community activity"
    indicatorQuery: "SELECT count(DISTINCT efm.base_entity_id) as count
                      FROM ec_sbc_register ear
                      INNER JOIN ec_family_member efm ON efm.base_entity_id = ear.base_entity_id
                      AND (date(efm.dob, '+15 years') <= date('now'))
                      AND (date(efm.dob, '+19 years') > date('now'))
                      AND (efm.gender='Female')
                      AND date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01')) =
                      date(substr(strftime('%Y-%m-%d', datetime(last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||
                      '-' || substr(strftime('%Y-%m-%d', datetime(last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) || '-' || '01')"

  - key: "sbc-1-female-20-24"
    description: "Number of individuals reached by specific SBC HIV community activity"
    indicatorQuery: "SELECT count(DISTINCT efm.base_entity_id) as count
                      FROM ec_sbc_register ear
                      INNER JOIN ec_family_member efm ON efm.base_entity_id = ear.base_entity_id
                      AND (date(efm.dob, '+20 years') <= date('now'))
                      AND (date(efm.dob, '+24 years') > date('now'))
                      AND (efm.gender='Female')
                      AND date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01')) =
                      date(substr(strftime('%Y-%m-%d', datetime(last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||
                      '-' || substr(strftime('%Y-%m-%d', datetime(last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) || '-' || '01')"

  - key: "sbc-1-female-25-29"
    description: "Number of individuals reached by specific SBC HIV community activity"
    indicatorQuery: "SELECT count(DISTINCT efm.base_entity_id) as count
                      FROM ec_sbc_register ear
                      INNER JOIN ec_family_member efm ON efm.base_entity_id = ear.base_entity_id
                      AND (date(efm.dob, '+25 years') <= date('now'))
                      AND (date(efm.dob, '+29 years') > date('now'))
                      AND (efm.gender='Female')
                      AND date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01')) =
                      date(substr(strftime('%Y-%m-%d', datetime(last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||
                      '-' || substr(strftime('%Y-%m-%d', datetime(last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) || '-' || '01')"

  - key: "sbc-1-female-30-34"
    description: "Number of individuals reached by specific SBC HIV community activity"
    indicatorQuery: "SELECT count(DISTINCT efm.base_entity_id) as count
                      FROM ec_sbc_register ear
                      INNER JOIN ec_family_member efm ON efm.base_entity_id = ear.base_entity_id
                      AND (date(efm.dob, '+30 years') <= date('now'))
                      AND (date(efm.dob, '+34 years') > date('now'))
                      AND (efm.gender='Female')
                      AND date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01')) =
                      date(substr(strftime('%Y-%m-%d', datetime(last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||
                      '-' || substr(strftime('%Y-%m-%d', datetime(last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) || '-' || '01')"

  - key: "sbc-1-female-35-39"
    description: "Number of individuals reached by specific SBC HIV community activity"
    indicatorQuery: "SELECT count(DISTINCT efm.base_entity_id) as count
                      FROM ec_sbc_register ear
                      INNER JOIN ec_family_member efm ON efm.base_entity_id = ear.base_entity_id
                      AND (date(efm.dob, '+35 years') <= date('now'))
                      AND (date(efm.dob, '+39 years') > date('now'))
                      AND (efm.gender='Female')
                      AND date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01')) =
                      date(substr(strftime('%Y-%m-%d', datetime(last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||
                      '-' || substr(strftime('%Y-%m-%d', datetime(last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) || '-' || '01')"

  - key: "sbc-1-female-40-44"
    description: "Number of individuals reached by specific SBC HIV community activity"
    indicatorQuery: "SELECT count(DISTINCT efm.base_entity_id) as count
                      FROM ec_sbc_register ear
                      INNER JOIN ec_family_member efm ON efm.base_entity_id = ear.base_entity_id
                      AND (date(efm.dob, '+40 years') <= date('now'))
                      AND (date(efm.dob, '+44 years') > date('now'))
                      AND (efm.gender='Female')
                      AND date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01')) =
                      date(substr(strftime('%Y-%m-%d', datetime(last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||
                      '-' || substr(strftime('%Y-%m-%d', datetime(last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) || '-' || '01')"

  - key: "sbc-1-female-45-49"
    description: "Number of individuals reached by specific SBC HIV community activity"
    indicatorQuery: "SELECT count(DISTINCT efm.base_entity_id) as count
                      FROM ec_sbc_register ear
                      INNER JOIN ec_family_member efm ON efm.base_entity_id = ear.base_entity_id
                      AND (date(efm.dob, '+45 years') <= date('now'))
                      AND (date(efm.dob, '+49 years') > date('now'))
                      AND (efm.gender='Female')
                      AND date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01')) =
                      date(substr(strftime('%Y-%m-%d', datetime(last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||
                      '-' || substr(strftime('%Y-%m-%d', datetime(last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) || '-' || '01')"

  - key: "sbc-1-female-50+"
    description: "Number of individuals reached by specific SBC HIV community activity"
    indicatorQuery: "SELECT count(DISTINCT efm.base_entity_id) as count
                      FROM ec_sbc_register ear
                      INNER JOIN ec_family_member efm ON efm.base_entity_id = ear.base_entity_id
                      AND (date('now')-date(efm.dob))>=50
                      AND (efm.gender='Female')
                      AND date((substr('%s', 1, 4) || '-' || substr('%s', 6, 2) || '-' || '01')) =
                      date(substr(strftime('%Y-%m-%d', datetime(last_interacted_with / 1000, 'unixepoch', 'localtime')), 1, 4) ||
                      '-' || substr(strftime('%Y-%m-%d', datetime(last_interacted_with / 1000, 'unixepoch', 'localtime')), 6, 2) || '-' || '01')"